config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  authenticated :user do
    root to: 'users#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/user.rb
# Top-level documentation comment for User module

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :email, confirmation: true
end

app/controllers/users_controller.rb
# Top-level documentation comment for UsersController module
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.includes(:posts).order(created_at: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<h1 class='center'>ACTIVE USERS</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <div class="user-div">
        <div class="photo">
          <% if user.photo.present? %>
            <%= image_tag user.photo, alt: "User Photo", class: "user-photo" %>
          <% else %>
            <span>No photo</span>
          <% end %>
        </div>
        <%= link_to user_path(user) do %>
          <div class="user-info">
            <span class="user-name"><%= user.name %></span>
            <span class="post-count">Number of posts: <%= user.posts.count %></span>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="user-div">
<div class="photo">
<% if @user.photo.present? %>
  <%= image_tag @user.photo, alt: "User Photo", class: "user-photo" %>
<% else %>
  <span>No photo</span>
<% end %>
</div>
<div class="user-info">
<span class="user-name"><%= @user.name %></span>
<span class="post-count">Number of posts: <%= @user.posts.count %></span>
</div>
</div>

<div class="wrap bio">
  <h4 class="title">Bio</h4>
  <p><%= @user.bio %></p>
</div>

<ul>
  <% @user.recent_posts.each_with_index do |post, index| %>
    <li class="post wrap list">
    <div>
      <h4 class="title list-title">Post <%= index+1  %>: <%= link_to post.title, user_post_path(@user, post) %></h4>
      <p class="post-text"><%= post.text %></p>
    </div>
      <div class="counters">
      <p class="small">Comments: <%= post.comments.count %></p>
      <p class="small">Likes: <%= post.likes.count %></p>
      </div>
    </li>
  <% end %>
</ul>
<div class="see-all-wrap">
<%= link_to user_posts_path(@user) do %>
<span class="see-all">See all posts</span>
<% end %>
<button type="button" class="see-all btn-post"><%= link_to "Create a post", new_user_post_path(@user)  %></button>
</div>