config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  authenticated :user do
    root to: 'users#index', as: :authenticated_root
  end

  root to: redirect('/users/sign_in')

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/post.rb
# Top-level documentation comment for Post module
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts

    render json: posts
  end
end

app/controllers/posts_controller.rb
# Top-level documentation comment for PostsController module
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to user_posts_path(current_user)
    else
      flash[:alert] = "Couln't create post!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    comments = @post.comments
    likes = @post.likes
    comments.destroy_all
    likes.destroy_all
    authorize! :destroy, @post

    if @post.destroy
      redirect_to user_posts_path, notice: 'Post deleted successfully.'
    else
      redirect_to user_posts_path, alert: 'Failed to delete the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/views/posts/index.html.erb
<div class="user-div">
<div class="photo">
<% if @user.photo.present? %>
  <%= image_tag @user.photo, alt: "User Photo", class: "user-photo" %>
<% else %>
  <span>No photo</span>
<% end %>
</div>
<div class="user-info">
<span class="user-name"><%= @user.name %></span>
<span class="post-count">Number of posts: <%= @user.posts_counter %></span>
</div>
</div>

  <ul>
  <% @user.posts.each do |post| %>
  <a href="<%= user_post_path(@user, post) %>">
    <li class="post wrap list">
    <div>
      <h4 class="title list-title"><%= post.title %></h4>
      <p class="post-text"><%= post.text %></p>
    </div>
      <div class="counters">
      <p class="small">Comments: <%= post.comments_counter %></p>
      <p class="small">Likes: <%= post.likes_counter %></p>
      </div>

      <% if can?(:destroy, post) %>
        <% user = User.find(params[:user_id]) %>
        <%= link_to 'Delete', user_post_path(user, post), data: { turbo_method: :delete, confirm: 'Are you sure you want to delete this post?' }, class: 'delete-button' %>
      <% end %>

    </li>
    </a>

    <div class="wrap list comment">
    <% post.recent_comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %></p>
    <% end %>
  </div>
  <% end %>
</ul>

app/views/posts/new.html.erb
<div class='center new-post'>
  
  <h3 class='center'>New Post</h3>
  <div class='center'>
  <%= render "shared/form", post: @post %>
  </div>
  <p class='center'><%=link_to 'Back to users', users_path %></p>
<div>

app/views/posts/show.html.erb
<div class="post wrap post-full">
    <div>
      <h4 class="title list-title post-title"><%= @post.title %> by <%= @post.author.name %></h4>
      <p class="post-text"><%= @post.text %></p>
    </div>
      <div class="counters post-counters">
      <p class="small">Comments: <%= @post.comments_counter %></p>

      <p class="small">Likes: <%= @post.likes_counter %></p>
      </div>
</div>

<div class='like-comment-wrap'>
<div>
  <%= form_with model: [@user, @post, @comment], url: user_post_comments_path(@user, @post), class: "form", local: true do |form| %>
    <div>
      <%= form.text_area :text, class: "text-area", placeholder: "Add a comment..." %>
    </div>
    <div class='comment-btn'>
      <%= form.submit "Comment", class: "see-all btn" %>
    </div>
  <% end %>
</div>

 <div>
      <%= form_with model: @like, url: user_post_likes_path(user_id: @post.author.id, post_id: @post.id), local: true do |form| %>
        <%= form.submit "Like", class: "see-all btn" %>
      <% end %>
    </div>
</div>



  <div class="wrap comment">
  <% @post.comments.each do |comment| %>
    <p>
      <%= comment.author.name %>: <%= comment.text %>
      <% if can?(:destroy, comment) %>
        <%= button_to 'Delete', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?'}, class: 'comment-button' %>
      <% end %>
    </p>
  <% end %>
</div>